import {beforeEach,afterAll,it,expect} from 'vitest';
import {Miniflare} from 'miniflare';
import {readFileSync} from 'node:fs';
import {Store} from '../src/storage';
import {handleUpdate,flush} from '../src/telegram_bot';
import worker from '../src/index';
const mf=new Miniflare({modules:true,script:'export default {fetch(){return new Response("ok")}}',d1Databases:['DB']});
let s:Store;let env:any;
beforeEach(async()=>{const db=await mf.getD1Database('DB');await db.exec(readFileSync('migrations/0001.sql','utf8').replace(/\n/g,' '));await db.batch(['events','outreach_queue','leads','outbox','inbound_sessions','suppression','inbox'].map(t=>db.prepare(`DELETE FROM ${t}`)));await db.prepare("UPDATE settings SET value='0'").run();s=new Store(db as any);env={DB:db,ADMIN_IDS:'123',ADMIN_CHAT_ID:'123',TELEGRAM_BOT_TOKEN:'fake',TELEGRAM_WEBHOOK_SECRET:'secure',SUPPRESSION_SALT:'test-secret'};});
afterAll(()=>mf.dispose());
const update=(text:string,id=999,n=1)=>({update_id:n,message:{message_id:n,from:{id},chat:{id,type:'private'},text}});
it('unauthorized admin cannot pause',async()=>{await handleUpdate(s,env,update('/pause'));expect(await s.get('paused')).toBe('0');});
it('owner can pause',async()=>{await handleUpdate(s,env,update('/pause',123));expect(await s.get('paused')).toBe('1');});
it('incoming briefing ends in CRM and owner queue',async()=>{for(const [i,t] of ['/start','Лендинг','нет','Форма заявки','нет','не срочно','3000','нет'].entries())await handleUpdate(s,env,update(t,999,i+1));const ls=await s.list('inbound');expect(ls).toHaveLength(1);expect(ls[0].text).toContain('Форма заявки');expect((await s.db.prepare("SELECT * FROM outbox WHERE chat_id='123'").all()).results).toHaveLength(1);});
it('ordinary question does not become a lead',async()=>{await handleUpdate(s,env,update('Как с вами связаться?'));expect(await s.list()).toHaveLength(0);});
it('opt out suppresses later messages',async()=>{await handleUpdate(s,env,update('/stop'));const n=(await s.db.prepare('SELECT * FROM outbox').all()).results.length;await handleUpdate(s,env,update('Здравствуйте',999,2));expect((await s.db.prepare('SELECT * FROM outbox').all()).results.length).toBe(n);});
it('confirmed notification delivery stored',async()=>{await s.enqueue('x','123','hello');expect(await flush(s,env,async()=>new Response(JSON.stringify({ok:true,result:{message_id:7}})) as any)).toBe(1);expect((await s.db.prepare('SELECT status FROM outbox').first<any>())?.status).toBe('sent');});
it('uncertain telegram delivery never duplicated',async()=>{await s.enqueue('x','123','hello');let n=0;const f=async()=>{n++;throw Error('token secret');};await flush(s,env,f as any);await flush(s,env,f as any);expect(n).toBe(1);expect((await s.db.prepare('SELECT status,error FROM outbox').first<any>())?.status).toBe('unknown');});
it('Telegram 429 rescheduled without leaking response',async()=>{await s.enqueue('x','123','hello');await flush(s,env,async()=>new Response(JSON.stringify({ok:false,error_code:429,parameters:{retry_after:30}})) as any);expect((await s.db.prepare('SELECT status FROM outbox').first<any>())?.status).toBe('pending');});
it('wrong webhook secret rejected',async()=>{const r=await worker.fetch(new Request('https://worker.example/webhook',{method:'POST',body:JSON.stringify(update('/pause',123))}),env,{} as any);expect(r.status).toBe(401);});
it('database failure returns safe 503 for Telegram retry',async()=>{const r=await worker.fetch(new Request('https://worker.example/webhook',{method:'POST',headers:{'X-Telegram-Bot-Api-Secret-Token':'secure'},body:JSON.stringify(update('/pause',123))}),{...env,DB:{prepare(){throw Error('database token secret');}}},{} as any);expect(r.status).toBe(503);expect(await r.text()).not.toContain('secret');});
it('private exports require owner API secret',async()=>{const r=await worker.fetch(new Request('https://worker.example/api/export'),env,{} as any);expect(r.status).toBe(401);});
