PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS leads (
 id TEXT PRIMARY KEY, content_key TEXT NOT NULL UNIQUE, url TEXT NOT NULL UNIQUE,
 source_id TEXT NOT NULL, category TEXT NOT NULL, priority TEXT NOT NULL, score INTEGER NOT NULL,
 status TEXT NOT NULL DEFAULT 'new', discovered_at INTEGER NOT NULL, published_at INTEGER,
 checked_at INTEGER NOT NULL, do_not_contact INTEGER NOT NULL DEFAULT 0, payload TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS leads_recent ON leads(discovered_at);
CREATE INDEX IF NOT EXISTS leads_category ON leads(category,score DESC);
CREATE INDEX IF NOT EXISTS leads_status ON leads(status,score DESC);
CREATE TABLE IF NOT EXISTS events (id INTEGER PRIMARY KEY AUTOINCREMENT, lead_id TEXT REFERENCES leads(id) ON DELETE CASCADE, type TEXT NOT NULL, detail TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS events_date ON events(created_at);
CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY,value TEXT NOT NULL);
INSERT OR IGNORE INTO settings VALUES ('paused','0'),('outbound_stopped','0');
CREATE TABLE IF NOT EXISTS source_state (id TEXT PRIMARY KEY, last_checked INTEGER NOT NULL DEFAULT 0, next_run INTEGER NOT NULL DEFAULT 0, failures INTEGER NOT NULL DEFAULT 0, error TEXT, inspected INTEGER NOT NULL DEFAULT 0, found INTEGER NOT NULL DEFAULT 0, enabled INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS leases (key TEXT PRIMARY KEY,owner TEXT NOT NULL,expires_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS quotas (key TEXT PRIMARY KEY,used INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS inbox (id INTEGER PRIMARY KEY, payload TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending', created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS inbox_status ON inbox(status,created_at);
CREATE TABLE IF NOT EXISTS outbox (id TEXT PRIMARY KEY, chat_id TEXT NOT NULL, text TEXT NOT NULL, keyboard TEXT, status TEXT NOT NULL DEFAULT 'pending', attempts INTEGER NOT NULL DEFAULT 0, next_attempt INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL, error TEXT, message_id INTEGER);
CREATE INDEX IF NOT EXISTS outbox_pending ON outbox(status,next_attempt);
CREATE TABLE IF NOT EXISTS inbound_sessions (chat_id TEXT PRIMARY KEY, step INTEGER NOT NULL, data TEXT NOT NULL, opted_out INTEGER NOT NULL DEFAULT 0, updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS suppression (contact_hash TEXT PRIMARY KEY,created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS outreach_queue (lead_id TEXT PRIMARY KEY REFERENCES leads(id) ON DELETE CASCADE, draft TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'review', consent INTEGER NOT NULL DEFAULT 0, platform_allowed INTEGER NOT NULL DEFAULT 0,recipient_verified INTEGER NOT NULL DEFAULT 0,updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS audit_jobs (url TEXT PRIMARY KEY, company TEXT NOT NULL, evidence TEXT NOT NULL DEFAULT '[]',status TEXT NOT NULL DEFAULT 'pending',checked_at INTEGER NOT NULL DEFAULT 0,result TEXT);
