import type {Fetcher,Problem} from './types';
import {getText,HttpFailure} from './http';
export function publicIP(ip:string):boolean {
 if(ip.includes(':'))return /^[23][0-9a-f]{0,3}:/i.test(ip)&&!/^2001:(?:db8|0):/i.test(ip);
 const xs=ip.split('.').map(Number);if(xs.length!==4||xs.some(x=>!Number.isInteger(x)||x<0||x>255))return false;
 const [a,b]=xs;return !([0,10,127,169,192].includes(a)||a>=224||(a===172&&b>=16&&b<=31)||(a===100&&b>=64&&b<=127)||(a===198&&(b===18||b===19)));
}
export function safeUrl(value:string):URL|null{try{const u=new URL(value);const h=u.hostname.toLowerCase().replace(/^\[|\]$/g,'');if(!['https:','http:'].includes(u.protocol)||u.username||u.password||(u.port&&!['80','443'].includes(u.port)))return null;if(h==='localhost'||h.endsWith('.localhost')||h.endsWith('.local')||h.endsWith('.internal')||!h.includes('.'))return null;if((/^[\d.]+$/.test(h)||h.includes(':'))&&!publicIP(h))return null;return u;}catch{return null;}}
export function robotsAllow(txt:string,url:string):boolean{
 const path=new URL(url).pathname+new URL(url).search;const groups:{agents:string[];rules:{path:string;allow:boolean}[]}[]=[];let group:{agents:string[];rules:{path:string;allow:boolean}[]}|null=null;
 for(const line of txt.split(/\r?\n/)){const [key,...rest]=line.split('#')[0].split(':');const value=rest.join(':').trim();const k=key.trim().toLowerCase();if(k==='user-agent'){if(!group||group.rules.length){group={agents:[],rules:[]};groups.push(group);}group.agents.push(value.toLowerCase());}else if(group&&(k==='allow'||k==='disallow')&&value)group.rules.push({path:value,allow:k==='allow'});}
 const specific=groups.filter(g=>g.agents.some(a=>a!=='*'&&'webleadmachine'.includes(a)));const active=specific.length?specific:groups.filter(g=>g.agents.includes('*'));const matches=active.flatMap(g=>g.rules).filter(r=>{const re=r.path.split('*').map(x=>x.replace(/[.+?^${}()|[\]\\]/g,'\\$&')).join('.*').replace(/\\\$$/,'$');return new RegExp('^'+re).test(path);}).sort((a,b)=>b.path.length-a.path.length||Number(b.allow)-Number(a.allow));return matches[0]?.allow??true;
}
export function auditHtml(html:string,now=Date.now()):Problem[]{const p:Problem[]=[];const add=(type:string,evidence:string,solution:string,severity:'medium'|'low'='low')=>p.push({type,severity,evidence,solution,checkedAt:now,costHint:'Оценить после проверки объёма; фиксированная цена не назначена.',confirmed:true});
 if(!/<meta\b[^>]*name\s*=\s*["']?viewport\b/i.test(html))add('viewport_missing','В полученном HTML нет meta[name=viewport].','Проверить адаптивность и добавить корректный viewport.','medium');
 if(!/<title\b[^>]*>\s*[^<\s][\s\S]*?<\/title>/i.test(html))add('title_missing','В HTML отсутствует непустой title.','Добавить название страницы.');
 if(!/<meta\b[^>]*name\s*=\s*["']?description\b/i.test(html))add('description_missing','В HTML нет meta description.','Составить описание страницы.');
 if(/<img\b[^>]*src\s*=\s*["']\s*["']/i.test(html))add('empty_image_src','Найден img с пустым src.','Исправить ссылку изображения.');
 return p;}
export interface AuditResult{url:string;state:'ok'|'blocked'|'uncertain'|'http_error';problems:Problem[];checkedAt:number;notes:string[];}
async function checkDNS(u:URL,fetcher:Fetcher){if(/^[\d.]+$/.test(u.hostname))return publicIP(u.hostname);const records:string[]=[];for(const type of ['A','AAAA']){const r=await getText(`https://cloudflare-dns.com/dns-query?name=${encodeURIComponent(u.hostname)}&type=${type}`,async(input,init)=>fetcher(input,{...init,headers:{...init?.headers,accept:'application/dns-json'}}),1);if(r.status!==200)throw new HttpFailure('dns_uncertain');const j=JSON.parse(r.text);if(j.Status!==0)throw new HttpFailure('dns_uncertain');for(const a of j.Answer??[])if(a.type===1||a.type===28)records.push(a.data);}return records.length>0&&records.every(publicIP);}
export async function audit(value:string,fetcher:Fetcher=fetch):Promise<AuditResult>{const now=Date.now();const u=safeUrl(value);const r:AuditResult={url:value,state:'ok',problems:[],checkedAt:now,notes:['Только статический HTML; формы и корзина не отправлялись, JS/скорость/дизайн не проверены.']};if(!u){r.state='blocked';r.notes.push('unsafe_url');return r;}
 try{if(!await checkDNS(u,fetcher)){r.state='blocked';r.notes.push('private_or_unresolved_address');return r;}const robots=await getText(new URL('/robots.txt',u).toString(),fetcher,1);if((robots.status!==200&&robots.status!==404)||robots.status===200&&!robotsAllow(robots.text,u.toString())){r.state='blocked';r.notes.push('robots_denied_or_unavailable');return r;}const page=await getText(u.toString(),fetcher,1);if(page.status>=300&&page.status<400){r.state='uncertain';r.notes.push('redirect_requires_manual_review');return r;}if(page.status>=400){r.state='http_error';r.problems.push({type:'http_'+page.status,severity:'high',evidence:`GET ответил HTTP ${page.status}; это не доказательство длительной недоступности.`,checkedAt:now,solution:'Повторить проверку и проверить сервер.',costHint:'После диагностики.',confirmed:true});return r;}if(page.status!==200||!page.contentType.includes('text/html')){r.state='uncertain';r.notes.push('not_html');return r;}r.problems=auditHtml(page.text,now);return r;}catch{r.state='uncertain';r.notes.push('network_or_dns_uncertain');return r;}}
export function verifyNoWebsite(evidence:{kind:'directory'|'official'|'search';url:string;claim:'active'|'missing'}[]):{state:'has_website'|'unverified'|'needs_manual_confirmation';evidence:typeof evidence}{if(evidence.some(x=>x.claim==='active'))return {state:'has_website',evidence};return {state:new Set(evidence.map(x=>x.kind)).size>=2?'needs_manual_confirmation':'unverified',evidence};}
